# This Travis CI file is for testing the build and functionality
# of the libFMScoupler library, and model executable.
#
# This Travis CI file is based off the NOAA-GFDL/FMS Travis CI
# file.

# The FMS coupler is not a c-language project, but this is the
# best choice under Travis CI.
language: c
dist: xenial
sudo: false

addons:
  atp:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config netcdf-bin libnetcdf-dev libnetcdff-dev openmpi-bin libopenmpi-dev gfortran

before_install:
  - test -n "$CC" && unset CC

before_script:
  - export CC=mpicc
  - export FC=mpif90
  - export CPPFLAGS='-I/usr/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500'
  - export FCFLAGS='-fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check'
  - export LDFLAGS='-L/usr/lib'

script:
  - t/null_model_build.sh
